import tkinter as tk
main = tk.Tk()
main.title("My webpage")
frame1=tk.Frame(main)
frame1.pack()
label1=tk.Label(frame1,text="Number : ",fg="black",font=("Arial",10))
label1.pack(side="left",pady=20)
entry1=tk.Entry(frame1,width=50)
entry1.pack(side="left")
frame2= tk.Frame(main)
frame2.pack()
btn5 = tk.Button(frame2, text="7", fg="black", width=11, height=2)
btn5.pack(side="left", padx=2,pady=10)
btn6 = tk.Button(frame2, text="8", fg="black", width=11, height=2)
btn6.pack(side="left", padx=2,pady=10)
btn7 = tk.Button(frame2, text="9", fg="black", width=11, height=2)
btn7.pack(side="left", padx=2,pady=10)
btn8 = tk.Button(frame2, text="*", fg="black", width=11, height=2)
btn8.pack(side="left", padx=2,pady=10)
frame3 = tk.Frame(main)
frame3.pack()
btn5 = tk.Button(frame3, text="4", fg="black", width=11, height=2)
btn5.pack(side="left", padx=2,pady=10)
btn6 = tk.Button(frame3, text="5", fg="black", width=11, height=2)
btn6.pack(side="left", padx=2,pady=10)
btn7 = tk.Button(frame3, text="6", fg="black", width=11, height=2)
btn7.pack(side="left", padx=2,pady=10)
btn8 = tk.Button(frame3, text="-", fg="black", width=11, height=2)
btn8.pack(side="left", padx=2,pady=10)
frame4 = tk.Frame(main)
frame4.pack()
btn5 = tk.Button(frame4, text="1", fg="black", width=11, height=2)
btn5.pack(side="left", padx=2,pady=10)
btn6 = tk.Button(frame4, text="2", fg="black", width=11, height=2)
btn6.pack(side="left", padx=2,pady=10)
btn7 = tk.Button(frame4, text="3", fg="black", width=11, height=2)
btn7.pack(side="left", padx=2,pady=10)
btn8 = tk.Button(frame4, text="+", fg="black", width=11, height=2)
btn8.pack(side="left", padx=2,pady=10)
frame5 = tk.Frame(main)
frame5.pack()
btn5 = tk.Button(frame5, text="/", fg="black", width=11, height=2)
btn5.pack(side="left", padx=2,pady=10)
btn6 = tk.Button(frame5, text="0", fg="black", width=11, height=2)
btn6.pack(side="left", padx=2,pady=10)
btn7 = tk.Button(frame5, text=".", fg="black", width=11, height=2)
btn7.pack(side="left", padx=2,pady=10)
def  hello():
    expression=entry1.get().strip()
    try:
        result = eval(expression)
        entry1.delete(0, tk.END)
        entry1.insert(0, str(result))
    except:
        print("Invalid choice.....!please choose the correct operation")
btn8 = tk.Button(frame5, text="=", fg="black", width=11, height=2,command=hello)
btn8.pack(side="left",padx=2,pady=10)      
main.geometry("400x500")
main.mainloop()