name=input("Enter your name:\n")
addmission_no=input("Enter your ad no:\n")
classs=input("Enter your class:\n")
contact_no=input("Enter your contact no:\n")
guardian=input("Enter your guardian:\n")
blood_group=input("Enter your blood group:\n")
place=input("Enter your place:\n")
gender=input("Enter your gender:\n")

print("-"*50)
print("name             :  "+name)
print("admission        :  "+addmission_no)
print("class            :  "+classs)
print("contact no       :  "+contact_no)
print("guardian         :  "+guardian)
print("blood group      :  "+blood_group)
print("place            :  "+place)
print("gender           :  "+gender)
print("-"*50)