# # # import tkinter as tk
# # # main=tk.Tk()
# # # main.title("My website")
# # # label1 =tk.Label(main,text="welcome",fg="blue",bg="black",padx=20,pady=20,font=("Arial",30))
# # # label1.pack(padx=200,pady=100)

# # # main.geometry("600x600")
# # # main.mainloop()


# # from tkinter import *
# # main = Tk()
# # main.title("My website")
# # label1 = Label(main,text="LOGIN PAGE",fg="red",padx=50,pady=50,font=("Arial",20))
# # label1.pack(padx=15,pady=15)
# # label3 = Label(main,text="Username",fg="red",padx=30,pady=30,font=("Arial",10))
# # label3.pack()
# # Entry1=Entry(main)
# # Entry1.pack()
# # label2 = Label(main,text="Password",fg="red",padx=30,pady=30,font=("Arial",10))
# # label2.pack()
# # Entry1=Entry(main)
# # Entry1.pack()
# # def hello():
# #     print("login successfull")
# # btn1=Button(main,text="Submit",fg="black",width=10,height=1,font=("Arial",10),command=hello)
# # btn1.pack(padx=15,pady=15)
# # main.geometry("600x600")
# # main.mainloop()


# from tkinter import *
# main = Tk()
# main.title("My website")
# label1 = Label(main,text="LOGIN PAGE",fg="blue",padx=50,pady=50,font=("Arial",20))
# label1.pack(padx=15,pady=15)
# label3 = Label(main,text="username",fg="blue",padx=30,pady=30,font=("Arial",10))
# label3.pack()
# Entry1=Entry(main)
# Entry1.pack()
# label2 = Label(main,text="password",fg="blue",padx=30,pady=30,font=("Arial",10))
# label2.pack()
# Entry1=Entry(main)
# Entry1.pack()
# def hello():
#     root=Tk()
#     root.title("My webpage")
#     label4 = Label(root,text="REGISTER PAGE",fg="red",padx=50,pady=50,font=("Arial",20))
#     label4.pack(padx=15,pady=15)
#     label5 = Label(root,text="Full Name",fg="red",padx=30,pady=30,font=("Arial",10))
#     label5.pack()
#     Entry6=Entry(root)
#     Entry6.pack()
#     label7 = Label(root,text="Email Id",fg="blue",padx=30,pady=30,font=("Arial",10))
#     label7.pack()
#     Entry8=Entry(root)
#     Entry8.pack()
#     label10 = Label(root,text="Password",fg="red",padx=30,pady=30,font=("Arial",10))
#     label10.pack()
#     Entry9=Entry(root)
#     Entry9.pack()
#     label11 = Label(root,text="Address",fg="red",padx=30,pady=30,font=("Arial",10))
#     label11.pack()
#     text1=Text(root,width=20,height=10,fg="red",font=("Arial",20))
#     text1.pack()
#     root.geometry("600x600")
#     root.mainloop()
# btn1=Button(main,text="submit",fg="black",width=10,height=1,font=("Arial",10),command=hello)
# btn1.pack(padx=15,pady=15)
# main.geometry("600x600")
# main.mainloop()


from tkinter import *
main = Tk()
main.title("My website")
label1 = Label(main,text="LOGIN PAGE",fg="blue",padx=50,pady=50,font=("Arial",20))
label1.pack(padx=15,pady=15)
label3 = Label(main,text="username",fg="blue",padx=30,pady=30,font=("Arial",10))
label3.pack()
Entry1=Entry(main)
Entry1.pack()
label2 = Label(main,text="password",fg="blue",padx=30,pady=30,font=("Arial",10))
label2.pack()
Entry1=Entry(main)
Entry1.pack()
def hello():
    root=Tk()
    root.title("My webpage")
    label4 = Label(root,text="REGISTER PAGE",fg="red",padx=50,pady=50,font=("Arial",20))
    label4.pack(padx=15,pady=15)
    label5 = Label(root,text="Full Name",fg="red",padx=30,pady=30,font=("Arial",10))
    label5.pack()
    Entry6=Entry(root)
    Entry6.pack()
    label7 = Label(root,text="Email Id",fg="blue",padx=30,pady=30,font=("Arial",10))
    label7.pack()
    Entry8=Entry(root)
    Entry8.pack()
    label10 = Label(root,text="Password",fg="red",padx=30,pady=30,font=("Arial",10))
    label10.pack()
    Entry9=Entry(root)
    Entry9.pack()
    label11 = Label(root,text="Address",fg="red",padx=30,pady=30,font=("Arial",10))
    label11.pack()
    text1=Text(root,width=20,height=2,fg="red",font=("Arial",20))
    text1.pack()
    btn4=Button(root,text="submit",fg="red",width=10,height=1,font=("Arial",10))
    btn4.pack(padx=15,pady=15)
    root.geometry("600x700")
    root.mainloop()
btn1=Button(main,text="submit",fg="black",width=10,height=1,font=("Arial",10),command=hello)
btn1.pack(padx=15,pady=15)
main.geometry("600x600")
main.mainloop()